language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install coveralls
  - pip install .
script:
  - python setup.py develop && coverage run --source=pwman setup.py test
after_success:
  - coveralls --verbose
